method: grid
metric:
  name: 'F1 Score (Weighted)'
  goal: maximize
parameters:
  C:
    values: [0.3, 0.5, 0.7, 1.0, 1.5]
  coef0:
    values: [0.3, 0.5, 0.7, 1.0, 1.5]
  degree:
    values: [1, 2, 3]
